### ISSUE TITLE
instructions lacking, errors hit

### ISSUE THREAD

**Issue by TeoTwawki** [gajeshbhat/Vidme-Creator-Backup#1]
project doesn't say if this requires python 2 or python 3.

The time package requirement is broken on both:

```
Could not find a version that satisfies the requirement time (from versions: )
No matching distribution found for time
```
wget, selenium, and bs4 are all ok though.

**Comment by TeoTwawki** [comment]
Apparently:
* it's python 2
* you never had to specify time`
* doesn't matter because nothing actually gets saved. script exits without error as if everything worked, but the specified directory didn't get anything saved to it.

**Comment by TeoTwawki** [comment]
really hoping appearances are wrong there

**Comment by gajeshbhat** [comment]
I have updated the requirements.txt file. Hope you are running the command in the proper format. 
Eg: python Vidme-Backup.py channel-name path-to-folder.

**Comment by TeoTwawki** [comment]
yeah thats how I ran it. but the output folder remained empty

**Comment by gajeshbhat** [comment]
I noticed there is some error with audio. I will be back in a couple of hours and fix it. Please feel free to fix it if you have time and create a pull request.

**Comment by gajeshbhat** [comment]
I think the video and audio have to be downloaded separately and then synced. Because vidme makes it difficult on purpose to extract their videos. Will do it when I get back from my exam this evening. Give me a couple of hours. Props to you for pointing it out.

**Comment by TeoTwawki** [comment]
props to you for taking the time to create this at all, let alone when you had exams coming up! good luck with exam 😄

**Comment by gajeshbhat** [comment]
I have updated the code and fixed some bugs. Please install ffmpeg for the code to work. New Command format: python Vidme-Backup.py channel-name
Videos will be downloaded in the same directory (Max Quality.)

**Comment by TeoTwawki** [comment]
hmm. still no luck. looks liek its working but then exits at command line without any error and no file written.

ffmeg is in my path, here is geckodriver log to it that'll help:

```
1513047464091	geckodriver	INFO	geckodriver 0.19.1
1513047464122	geckodriver	INFO	Listening on 127.0.0.1:11442
1513047466103	mozrunner::runner	INFO	Running command: "D:\\App\\Mozilla Firefox\\firefox.exe" "-marionette" "-headless" "-profile" "C:\\Users\\Arawn\\AppData\\Local\\Temp\\rust_mozprofile.WIwtmck1hhoS"
*** You are running in headless mode.
1513047466496	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///D:/App/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1513047466766	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\Teo\AppData\Local\openvr\openvrpaths.vrpath
[Parent 12760] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\Teo\AppData\Local\openvr\openvrpaths.vrpath
[Child 13140] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1513047467717	Marionette	INFO	Listening on port 11448
1513047467854	Marionette	WARN	TLS certificate errors will be ignored for this session
1513047467895	Marionette	DEBUG	Register listener.js for window 4294967297
1513047467913	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1513047468563	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1513047468564	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1513047471716	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://savieo.com/download?url=https%3A%2F%2Fvid.me%2F6hgc1"
1513047472104	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "4294967301"
Unable to read VR Path Registry from C:\Users\Teo\AppData\Local\openvr\openvrpaths.vrpath
JavaScript error: http://savieo.com/static/js/vendor/require-2.1.22.js, line 165: Error: Load timeout for modules: jquery,backbone,bootstrap
http://requirejs.org/docs/errors.html#timeout

**Comment by gajeshbhat** [comment]
I think you have to reinstall the gecko driver. The issue seems to be the driver, not the code. I have Installed gecko driver and its working just fine on my system.

**Comment by gajeshbhat** [comment]
Maybe the Issue is with gecko driver and windows. Please try to google the error. I use Linux and its running just fine.

**Comment by TeoTwawki** [comment]
installation on window sis as simple as download and make sure exe is in the path. There is not really anything more I can do for that.

man, if only vid.me gave us more time to get this done.

**Comment by TeoTwawki** [comment]
going to try downgrading geckodriver to an older version, crossing my fingers

**Comment by gajeshbhat** [comment]
Sure. Yes, Vidme did a poor job in ending its operations. They Just gave a deadline and an explanation. That's all. They didn't even care about the community.

**Comment by gajeshbhat** [comment]
If things dont work out on windows. Try using Linux Live Key or Virtual Machine to download the videos. It's Working flawlessly on my machine. Please also do spread the word about this repo so that a lot of people can benefit.

**Comment by TeoTwawki** [comment]
sidenote: these things seem to happen anything I have to use anyone's python based *anything*  on windblows instead of *\nix. its the snake curse I tell you.

**Comment by TeoTwawki** [comment]
...I just use the creator ID not the full url right? After downgrading gecko I'm getting different behavior than I recall (still non working, but an actual error this time)
```
Traceback (most recent call last):
  File "Vidme-Backup.py", line 86, in <module>
    video_downloader(videos_list)
  File "Vidme-Backup.py", line 51, in video_downloader
    video_name_soup = BeautifulSoup(video_name_link_src,"lxml")
  File "D:\Python\Python2\lib\site-packages\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lx
ml. Do you need to install a parser library?
```

**Comment by gajeshbhat** [comment]
try using the latest version of the beautiful soup.

**Comment by TeoTwawki** [comment]
according to pip the package bs4 is already on its latest version.

**Comment by gajeshbhat** [comment]
The current Issue is solved.Hope you can find the Windows OS specific solutions on the internet.
